apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: arm64v8/busybox:latest
        command:
          - sleep
          - "3600"
