apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: arm64v8/ubuntu:16.04
